export const SUPPORTED_CATEGORIES = [
  "angles",
  "area",
  "calorie",
  "currency",
  "current",
  "data",
  "density",
  "distance",
  "dynamic-viscosity",
  "electric-charge",
  "energy",
  "force",
  "frequency",
  "fuel-consumption",
  "illumination",
  "kinetic-viscosity",
  "moment-of-inertia",
  "numbers",
  "power",
  "prefixes",
  "pressure",
  "radiation-absorbed",
  "radioactivity",
  "speed",
  "strength",
  "temperature",
  "time",
  "torque",
  "typography",
  "vacuum",
  "volume",
  "volume-flow-rate",
  "weight",
] as const;

export type SupportedCategory = (typeof SUPPORTED_CATEGORIES)[number];
