// Auto-generated unit definitions for electric-charge
// Base unit: coulomb
// Last updated: 2026-03-13
import { UnitDefinition } from "../types/unit";


export const electricChargeUnits: UnitDefinition[] = [
  // ── Electric Charge Units ──
  {
    key: "coulomb",
    label: "Coulomb",
    symbol: "C",
    toBase: (v: number) => v,
    fromBase: (v: number) => v,
  },
  {
    key: "abcoulomb",
    label: "Abcoulomb",
    symbol: "abC",
    toBase: (v: number) => v * 10,
    fromBase: (v: number) => v / 10,
  },
  {
    key: "ampere-second",
    label: "Ampere-second",
    symbol: "A.s",
    toBase: (v: number) => v * 1,
    fromBase: (v: number) => v / 1,
  },
  {
    key: "atomic-unit",
    label: "Atomic unit",
    symbol: "e",
    toBase: (v: number) => v * 1.60218e-19,
    fromBase: (v: number) => v / 1.60218e-19,
  },
  {
    key: "centicoulomb",
    label: "Centi coulomb",
    symbol: "cC",
    toBase: (v: number) => v * 0.01,
    fromBase: (v: number) => v / 0.01,
  },
  {
    key: "charge-emu",
    label: "Charge emu",
    symbol: "emu",
    toBase: (v: number) => v * 10,
    fromBase: (v: number) => v / 10,
  },
  {
    key: "charge-esu",
    label: "Charge esu",
    symbol: "esu",
    toBase: (v: number) => v * 3.335641e-10,
    fromBase: (v: number) => v / 3.335641e-10,
  },
  {
    key: "decacoulomb",
    label: "Deca coulomb",
    symbol: "daC",
    toBase: (v: number) => v * 10,
    fromBase: (v: number) => v / 10,
  },
  {
    key: "decicoulomb",
    label: "Deci coulomb",
    symbol: "dC",
    toBase: (v: number) => v * 0.1,
    fromBase: (v: number) => v / 0.1,
  },
  {
    key: "faraday",
    label: "Faraday",
    symbol: "F",
    toBase: (v: number) => v * 96485.33,
    fromBase: (v: number) => v / 96485.33,
  },
  {
    key: "franklin",
    label: "Franklin",
    symbol: "Fr",
    toBase: (v: number) => v * 3.335641e-10,
    fromBase: (v: number) => v / 3.335641e-10,
  },
  {
    key: "gigacoulomb",
    label: "Giga coulomb",
    symbol: "gC",
    toBase: (v: number) => v * 1000000000,
    fromBase: (v: number) => v / 1000000000,
  },
  {
    key: "hectocoulomb",
    label: "Hecto coulomb",
    symbol: "hC",
    toBase: (v: number) => v * 100,
    fromBase: (v: number) => v / 100,
  },
  {
    key: "kilo-ampere-second",
    label: "Kilo ampere-second",
    symbol: "kA.s",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "kilocoulomb",
    label: "Kilo coulomb",
    symbol: "kC",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "mega-ampere-second",
    label: "Mega ampere-second",
    symbol: "MA.s",
    toBase: (v: number) => v * 1000000,
    fromBase: (v: number) => v / 1000000,
  },
  {
    key: "megacoulomb",
    label: "Mega coulomb",
    symbol: "MC",
    toBase: (v: number) => v * 1000000,
    fromBase: (v: number) => v / 1000000,
  },
  {
    key: "micro-ampere-second",
    label: "Micro ampere-second",
    symbol: "µA.s",
    toBase: (v: number) => v * 0.000001,
    fromBase: (v: number) => v / 0.000001,
  },
  {
    key: "microcoulomb",
    label: "Micro coulomb",
    symbol: "µC",
    toBase: (v: number) => v * 0.000001,
    fromBase: (v: number) => v / 0.000001,
  },
  {
    key: "milli-ampere-second",
    label: "Milli ampere-second",
    symbol: "mA.s",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "millicoulomb",
    label: "Milli coulomb",
    symbol: "mC",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "nanocoulomb",
    label: "Nano coulomb",
    symbol: "nC",
    toBase: (v: number) => v * 1e-9,
    fromBase: (v: number) => v / 1e-9,
  },
  {
    key: "picocoulomb",
    label: "Pico coulomb",
    symbol: "pC",
    toBase: (v: number) => v * 1e-12,
    fromBase: (v: number) => v / 1e-12,
  },
  {
    key: "statcoulomb",
    label: "Statcoulomb",
    symbol: "statC",
    toBase: (v: number) => v * 3.335641e-10,
    fromBase: (v: number) => v / 3.335641e-10,
  },
  {
    key: "teracoulomb",
    label: "Tera coulomb",
    symbol: "tC",
    toBase: (v: number) => v * 1000000000000,
    fromBase: (v: number) => v / 1000000000000,
  },
];
