// Auto-generated unit definitions for prefixes
// Base unit: none
// Last updated: 2026-03-13
import { UnitDefinition } from "../types/unit";


export const prefixesUnits: UnitDefinition[] = [
  // ── SI Prefixes ──
  {
    key: "none",
    label: "None",
    symbol: "none",
    toBase: (v: number) => v,
    fromBase: (v: number) => v,
  },
  {
    key: "yocto",
    label: "Yocto",
    symbol: "y",
    toBase: (v: number) => v * 1e-24,
    fromBase: (v: number) => v / 1e-24,
  },
  {
    key: "zepto",
    label: "Zepto",
    symbol: "z",
    toBase: (v: number) => v * 1e-21,
    fromBase: (v: number) => v / 1e-21,
  },
  {
    key: "atto",
    label: "Atto",
    symbol: "a",
    toBase: (v: number) => v * 1e-18,
    fromBase: (v: number) => v / 1e-18,
  },
  {
    key: "femto",
    label: "Femto",
    symbol: "f",
    toBase: (v: number) => v * 1e-15,
    fromBase: (v: number) => v / 1e-15,
  },
  {
    key: "pico",
    label: "Pico",
    symbol: "p",
    toBase: (v: number) => v * 1e-12,
    fromBase: (v: number) => v / 1e-12,
  },
  {
    key: "nano",
    label: "Nano",
    symbol: "n",
    toBase: (v: number) => v * 1e-9,
    fromBase: (v: number) => v / 1e-9,
  },
  {
    key: "micro",
    label: "Micro",
    symbol: "µ",
    toBase: (v: number) => v * 0.000001,
    fromBase: (v: number) => v / 0.000001,
  },
  {
    key: "milli",
    label: "Milli",
    symbol: "m",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "centi",
    label: "Centi",
    symbol: "c",
    toBase: (v: number) => v * 0.01,
    fromBase: (v: number) => v / 0.01,
  },
  {
    key: "deci",
    label: "Deci",
    symbol: "d",
    toBase: (v: number) => v * 0.1,
    fromBase: (v: number) => v / 0.1,
  },
  {
    key: "deca",
    label: "Deca",
    symbol: "da",
    toBase: (v: number) => v * 10,
    fromBase: (v: number) => v / 10,
  },
  {
    key: "hecto",
    label: "Hecto",
    symbol: "h",
    toBase: (v: number) => v * 100,
    fromBase: (v: number) => v / 100,
  },
  {
    key: "kilo",
    label: "Kilo",
    symbol: "k",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "mega",
    label: "Mega",
    symbol: "M",
    toBase: (v: number) => v * 1000000,
    fromBase: (v: number) => v / 1000000,
  },
  {
    key: "giga",
    label: "Giga",
    symbol: "G",
    toBase: (v: number) => v * 1000000000,
    fromBase: (v: number) => v / 1000000000,
  },
  {
    key: "tera",
    label: "Tera",
    symbol: "T",
    toBase: (v: number) => v * 1000000000000,
    fromBase: (v: number) => v / 1000000000000,
  },
  {
    key: "peta",
    label: "Peta",
    symbol: "P",
    toBase: (v: number) => v * 1000000000000000,
    fromBase: (v: number) => v / 1000000000000000,
  },
  {
    key: "exa",
    label: "Exa",
    symbol: "exa",
    toBase: (v: number) => v * 1000000000000000000,
    fromBase: (v: number) => v / 1000000000000000000,
  },
  {
    key: "zetta",
    label: "Zetta",
    symbol: "Z",
    toBase: (v: number) => v * 1e+21,
    fromBase: (v: number) => v / 1e+21,
  },
  {
    key: "yotta",
    label: "Yotta",
    symbol: "Y",
    toBase: (v: number) => v * 1e+24,
    fromBase: (v: number) => v / 1e+24,
  },

  // ── Binary Prefixes ──
  {
    key: "kibi",
    label: "Kibi",
    symbol: "Ki",
    toBase: (v: number) => v * 1024,
    fromBase: (v: number) => v / 1024,
  },
  {
    key: "mebi",
    label: "Mebi",
    symbol: "Mi",
    toBase: (v: number) => v * 1048576,
    fromBase: (v: number) => v / 1048576,
  },
  {
    key: "gibi",
    label: "Gibi",
    symbol: "Gi",
    toBase: (v: number) => v * 1073741824,
    fromBase: (v: number) => v / 1073741824,
  },
  {
    key: "tebi",
    label: "Tebi",
    symbol: "Ti",
    toBase: (v: number) => v * 1099511627776,
    fromBase: (v: number) => v / 1099511627776,
  },
  {
    key: "pebi",
    label: "Pebi",
    symbol: "Pi",
    toBase: (v: number) => v * 1125899906842624,
    fromBase: (v: number) => v / 1125899906842624,
  },
  {
    key: "exbi",
    label: "Exbi",
    symbol: "exbi",
    toBase: (v: number) => v * (2 ** 60),
    fromBase: (v: number) => v / (2 ** 60),
  },
];
