// Auto-generated unit definitions for radiation-absorbed
// Base unit: gray
// Last updated: 2026-03-13
import { UnitDefinition } from "../types/unit";


export const radiationAbsorbedUnits: UnitDefinition[] = [
  // ── Radiation Absorbed Units ──
  {
    key: "gray",
    label: "Gray",
    symbol: "Gy",
    toBase: (v: number) => v,
    fromBase: (v: number) => v,
  },
  {
    key: "attogray",
    label: "Attogray",
    symbol: "aGy",
    toBase: (v: number) => v * 1e-18,
    fromBase: (v: number) => v / 1e-18,
  },
  {
    key: "centigray",
    label: "Centigray",
    symbol: "cGy",
    toBase: (v: number) => v * 0.01,
    fromBase: (v: number) => v / 0.01,
  },
  {
    key: "decigray",
    label: "Decigray",
    symbol: "dGy",
    toBase: (v: number) => v * 0.1,
    fromBase: (v: number) => v / 0.1,
  },
  {
    key: "dekagray",
    label: "Dekagray",
    symbol: "daGy",
    toBase: (v: number) => v * 10,
    fromBase: (v: number) => v / 10,
  },
  {
    key: "exagray",
    label: "Exagray",
    symbol: "EGy",
    toBase: (v: number) => v * 1000000000000000000,
    fromBase: (v: number) => v / 1000000000000000000,
  },
  {
    key: "femtogray",
    label: "Femtogray",
    symbol: "fGy",
    toBase: (v: number) => v * 1e-15,
    fromBase: (v: number) => v / 1e-15,
  },
  {
    key: "gigagray",
    label: "Gigagray",
    symbol: "GGy",
    toBase: (v: number) => v * 1000000000,
    fromBase: (v: number) => v / 1000000000,
  },
  {
    key: "hectogray",
    label: "Hectogray",
    symbol: "hGy",
    toBase: (v: number) => v * 100,
    fromBase: (v: number) => v / 100,
  },
  {
    key: "joule-per-cg",
    label: "Joule/cg",
    symbol: "J/cg",
    toBase: (v: number) => v * 100,
    fromBase: (v: number) => v / 100,
  },
  {
    key: "joule-per-gram",
    label: "Joule/gram",
    symbol: "J/g",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "joule-per-kg",
    label: "Joule/kg",
    symbol: "J/kg",
    toBase: (v: number) => v * 1,
    fromBase: (v: number) => v / 1,
  },
  {
    key: "joule-per-mg",
    label: "Joule/mg",
    symbol: "J/mg",
    toBase: (v: number) => v * 1000000,
    fromBase: (v: number) => v / 1000000,
  },
  {
    key: "kilogray",
    label: "Kilogray",
    symbol: "kGy",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "megagray",
    label: "Megagray",
    symbol: "MGy",
    toBase: (v: number) => v * 1000000,
    fromBase: (v: number) => v / 1000000,
  },
  {
    key: "microgray",
    label: "Microgray",
    symbol: "µGy",
    toBase: (v: number) => v * 0.000001,
    fromBase: (v: number) => v / 0.000001,
  },
  {
    key: "microsievert",
    label: "Microsievert",
    symbol: "µSv",
    toBase: (v: number) => v * 0.000001,
    fromBase: (v: number) => v / 0.000001,
  },
  {
    key: "milligray",
    label: "Milligray",
    symbol: "mGy",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "millirad",
    label: "Millirad",
    symbol: "mrd",
    toBase: (v: number) => v * 0.00001,
    fromBase: (v: number) => v / 0.00001,
  },
  {
    key: "millisievert",
    label: "Millisievert",
    symbol: "mSv",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "nanogray",
    label: "Nanogray",
    symbol: "nGy",
    toBase: (v: number) => v * 1e-9,
    fromBase: (v: number) => v / 1e-9,
  },
  {
    key: "petagray",
    label: "Petagray",
    symbol: "PGy",
    toBase: (v: number) => v * 1000000000000000,
    fromBase: (v: number) => v / 1000000000000000,
  },
  {
    key: "picogray",
    label: "Picogray",
    symbol: "pGy",
    toBase: (v: number) => v * 1e-12,
    fromBase: (v: number) => v / 1e-12,
  },
  {
    key: "rad",
    label: "Rad",
    symbol: "rd",
    toBase: (v: number) => v * 0.01,
    fromBase: (v: number) => v / 0.01,
  },
  {
    key: "sievert",
    label: "Sievert",
    symbol: "Sv",
    toBase: (v: number) => v * 1,
    fromBase: (v: number) => v / 1,
  },
  {
    key: "teragray",
    label: "Teragray",
    symbol: "TGy",
    toBase: (v: number) => v * 1000000000000,
    fromBase: (v: number) => v / 1000000000000,
  },
];
