// Auto-generated unit definitions for volume
// Base unit: liter
// Last updated: 2026-03-13
import { UnitDefinition } from "../types/unit";


export const volumeUnits: UnitDefinition[] = [
  // ── Volume Units ──
  {
    key: "liter",
    label: "Liter",
    symbol: "l",
    toBase: (v: number) => v,
    fromBase: (v: number) => v,
  },
  {
    key: "milliliter",
    label: "Milliliter",
    symbol: "ml",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "cubic-centimeter",
    label: "Cubic centimeter",
    symbol: "cm³",
    toBase: (v: number) => v * 0.001,
    fromBase: (v: number) => v / 0.001,
  },
  {
    key: "cubic-meter",
    label: "Cubic meter",
    symbol: "m³",
    toBase: (v: number) => v * 1000,
    fromBase: (v: number) => v / 1000,
  },
  {
    key: "cubic-foot",
    label: "Cubic foot",
    symbol: "ft³",
    toBase: (v: number) => v * 28.316847,
    fromBase: (v: number) => v / 28.316847,
  },
  {
    key: "cubic-inch",
    label: "Cubic inch",
    symbol: "in³",
    toBase: (v: number) => v * 0.016387064,
    fromBase: (v: number) => v / 0.016387064,
  },
  {
    key: "cup",
    label: "Cup",
    symbol: "cups",
    toBase: (v: number) => v * 0.2365882,
    fromBase: (v: number) => v / 0.2365882,
  },
  {
    key: "dram-us",
    label: "Dram (US)",
    symbol: "dram",
    toBase: (v: number) => v * 0.003696691,
    fromBase: (v: number) => v / 0.003696691,
  },
  {
    key: "fluid-ounce-uk",
    label: "Fluid ounce (UK)",
    symbol: "fl.oz.",
    toBase: (v: number) => v * 0.0284131,
    fromBase: (v: number) => v / 0.0284131,
  },
  {
    key: "fluid-ounce-us",
    label: "Fluid ounce (US)",
    symbol: "fl.oz.",
    toBase: (v: number) => v * 0.0295735,
    fromBase: (v: number) => v / 0.0295735,
  },
  {
    key: "gallon-uk",
    label: "Gallon (UK)",
    symbol: "gal",
    toBase: (v: number) => v * 4.54609,
    fromBase: (v: number) => v / 4.54609,
  },
  {
    key: "gallon-us",
    label: "Gallon (US)",
    symbol: "gal",
    toBase: (v: number) => v * 3.785412,
    fromBase: (v: number) => v / 3.785412,
  },
  {
    key: "hectoliter",
    label: "Hectoliter",
    symbol: "hl",
    toBase: (v: number) => v * 100,
    fromBase: (v: number) => v / 100,
  },
  {
    key: "oil-barrel",
    label: "Oil Barrel",
    symbol: "bbl",
    toBase: (v: number) => v * 158.9873,
    fromBase: (v: number) => v / 158.9873,
  },
  {
    key: "pint-uk",
    label: "Pint (UK)",
    symbol: "pt",
    toBase: (v: number) => v * 0.568261,
    fromBase: (v: number) => v / 0.568261,
  },
  {
    key: "pint-us-dry",
    label: "Pint (US, dry)",
    symbol: "pt",
    toBase: (v: number) => v * 0.55061,
    fromBase: (v: number) => v / 0.55061,
  },
  {
    key: "pint-us-liquid",
    label: "Pint (US, liquid)",
    symbol: "pt",
    toBase: (v: number) => v * 0.473176,
    fromBase: (v: number) => v / 0.473176,
  },
  {
    key: "quart-uk",
    label: "Quart (UK)",
    symbol: "qt",
    toBase: (v: number) => v * 1.13652,
    fromBase: (v: number) => v / 1.13652,
  },
  {
    key: "quart-us",
    label: "Quart (US)",
    symbol: "qt",
    toBase: (v: number) => v * 0.946353,
    fromBase: (v: number) => v / 0.946353,
  },
  {
    key: "quart-us-liquid",
    label: "Quart (US, liquid)",
    symbol: "qt",
    toBase: (v: number) => v * 0.946353,
    fromBase: (v: number) => v / 0.946353,
  },
  {
    key: "tablespoon",
    label: "Tablespoon",
    symbol: "tbs",
    toBase: (v: number) => v * 0.0147868,
    fromBase: (v: number) => v / 0.0147868,
  },
  {
    key: "teaspoon",
    label: "Teaspoon",
    symbol: "tsp",
    toBase: (v: number) => v * 0.00492892,
    fromBase: (v: number) => v / 0.00492892,
  },
  {
    key: "bushel-uk",
    label: "Bushel (UK)",
    symbol: "UK.bu.",
    toBase: (v: number) => v * 36.36872,
    fromBase: (v: number) => v / 36.36872,
  },
  {
    key: "bushel-us",
    label: "Bushel (US)",
    symbol: "US.bu.",
    toBase: (v: number) => v * 35.23907,
    fromBase: (v: number) => v / 35.23907,
  },
];
